In [144]:
import pandas as pd
import numpy as np
from scipy.stats import mode


### 파일 불러오기

In [ ]:
screening_data = pd.read_excel("data/건강검진테이블1_1000.xlsx")
diagnois_data = pd.read_excel("의과및보건기관상병내역_개선버전.xlsx")

In [146]:
diagnois_data

RN_INDI         RN_KEY  MDCARE_STRT_DT  FORM_CD MCEX_SICK_SYM  \
0        596535  2002120187152        20021202        3          J209   
1        615374  2002121012274        20021202        3          J209   
2       1005547  2002120808216        20021202        3          J209   
3        226594  2002120381612        20021202        3          J209   
4        204930  2002120790182        20021202        3          J209   
...         ...            ...             ...      ...           ...   
340591  2089576  2015082315258        20150810        3          J320   
340592  2089576  2015082312462        20150824        3          J320   
340593  2090701  2015012530018        20150117        3            F_   
340594  2090701  2015062184186        20150627        3            F_   
340595  2090701  2015062184456        20150613        3            F_   

       DETAIL_TMSG_SUBJ_CD  SICK_CLSF_TYPE  STD_YYYY  대분류   소분류  
0                      NaN             NaN      2002  J20  J209  
1                      NaN             NaN      2002  J20  J209  
2                      NaN             NaN      2002  J20  J209  
3                      NaN             NaN      2002  J20  J209  
4                      NaN             NaN      2002  J20  J209  
...                    ...             ...       ...  ...   ...  
340591                  00             1.0      2015  J32  J320  
340592                  00             1.0      2015  J32  J320  
340593                 NaN             1.0      2015   F_    F_  
340594                 NaN             1.0      2015   F_    F_  
340595                 NaN             1.0      2015   F_    F_  

[340596 rows x 10 columns]

### 변수 값 수정
- 날짜가 앞자리는 16진수로 저장되어있어 string type으로 수정

In [147]:
screening_data["HME_YYYYMM"][0].strip().split("_")

['', 'x0032', '00211']

In [148]:
modify_screening_data = screening_data.copy()
modify_screening_data["HME_YYYYMM"] = ['2'+str(day).strip().split('_')[2] for day in screening_data["HME_YYYYMM"]]
modify_screening_data["EXMD_BZ_YYYY"] = ['2'+str(day).strip().split('_')[2] for day in screening_data["EXMD_BZ_YYYY"]]

In [149]:
modify_screening_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_PHX1_DZ_V0208  Q_PHX1_YR  Q_PHX1_CR  \
0            2002   572493     200211              0.0        NaN        NaN   
1            2002   874800     200207              0.0        NaN        NaN   
2            2002    88450     200207              0.0        NaN        NaN   
3            2002    56993     200212              0.0        NaN        NaN   
4            2002   591264     200210              0.0        NaN        NaN   
...           ...      ...        ...              ...        ...        ...   
1046         2008   218649     200806              1.0     1982.0        1.0   
1047         2008    39217     200812              NaN        NaN        NaN   
1048         2008   756414     200812              NaN        NaN        NaN   
1049         2008   642899     200806              NaN        NaN        NaN   
1050         2008   238542     200806              2.0     1991.0        2.0   

      Q_PHX2_DZ_V0208  Q_PHX2_YR  Q_PHX2_CR  Q_PHX3_DZ_V0208  ...  \
0                 0.0        NaN        NaN              0.0  ...   
1                 0.0        NaN        NaN              0.0  ...   
2                 0.0        NaN        NaN              0.0  ...   
3                 0.0        NaN        NaN              0.0  ...   
4                 0.0        NaN        NaN              0.0  ...   
...               ...        ...        ...              ...  ...   
1046              NaN        NaN        NaN              NaN  ...   
1047              NaN        NaN        NaN              NaN  ...   
1048              NaN        NaN        NaN              NaN  ...   
1049              NaN        NaN        NaN              NaN  ...   
1050              NaN        NaN        NaN              NaN  ...   

      G1E_URN_OCC_BLD  G1E_URN_PH  G1E_HGB  G1E_FBS  G1E_TOT_CHOL  G1E_SGOT  \
0                 1.0         6.0     13.3     75.0           216        26   
1                 1.0         6.0     15.2    108.0           194        27   
2                 1.0         6.0     14.0     81.0           196        22   
3                 1.0         6.0     14.7     89.0           159        12   
4                 1.0         6.0     17.2    104.0           198        33   
...               ...         ...      ...      ...           ...       ...   
1046              1.0         6.0     16.1     84.0           264        31   
1047              1.0         6.0     13.8    225.0           265        38   
1048              1.0         7.0     13.2    117.0           178        88   
1049              1.0         6.0     11.3     68.0           177        49   
1050              1.0         6.5     15.4     84.0           203        84   

      G1E_SGPT  G1E_GGT  G1E_CHST_XRAY_RST G1E_EKG_RST  
0           30     12.0                1.0         NaN  
1           37     21.0                1.0         1.0  
2           17     10.0                1.0         1.0  
3           19     76.0                1.0         NaN  
4           33     34.0                1.0         NaN  
...        ...      ...                ...         ...  
1046        39     75.0                1.0         NaN  
1047        41    146.0                1.0         1.0  
1048       171    126.0                1.0         1.0  
1049        32    154.0                1.0         1.0  
1050        47     74.0                1.0         2.0  

[1051 rows x 51 columns]

In [150]:
modify_diagnois_data = diagnois_data.copy()


In [151]:
modify_diagnois_data


RN_INDI         RN_KEY  MDCARE_STRT_DT  FORM_CD MCEX_SICK_SYM  \
0        596535  2002120187152        20021202        3          J209   
1        615374  2002121012274        20021202        3          J209   
2       1005547  2002120808216        20021202        3          J209   
3        226594  2002120381612        20021202        3          J209   
4        204930  2002120790182        20021202        3          J209   
...         ...            ...             ...      ...           ...   
340591  2089576  2015082315258        20150810        3          J320   
340592  2089576  2015082312462        20150824        3          J320   
340593  2090701  2015012530018        20150117        3            F_   
340594  2090701  2015062184186        20150627        3            F_   
340595  2090701  2015062184456        20150613        3            F_   

       DETAIL_TMSG_SUBJ_CD  SICK_CLSF_TYPE  STD_YYYY  대분류   소분류  
0                      NaN             NaN      2002  J20  J209  
1                      NaN             NaN      2002  J20  J209  
2                      NaN             NaN      2002  J20  J209  
3                      NaN             NaN      2002  J20  J209  
4                      NaN             NaN      2002  J20  J209  
...                    ...             ...       ...  ...   ...  
340591                  00             1.0      2015  J32  J320  
340592                  00             1.0      2015  J32  J320  
340593                 NaN             1.0      2015   F_    F_  
340594                 NaN             1.0      2015   F_    F_  
340595                 NaN             1.0      2015   F_    F_  

[340596 rows x 10 columns]

In [ ]:
screening2_data = pd.read_excel("data/건강검진테이블2_1000.xlsx")
modify_screening2_data = screening2_data.copy()
modify_screening2_data["HME_YYYYMM"] = ['2'+str(day).strip().split('_')[2] for day in screening2_data["HME_YYYYMM"]]
modify_screening2_data["EXMD_BZ_YYYY"] = ['2'+str(day).strip().split('_')[2] for day in screening2_data["EXMD_BZ_YYYY"]]

### 건강검진테이블2과 변수를 통일화 하기

In [153]:
merge_data = modify_screening_data.copy()

In [154]:
merge_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_PHX1_DZ_V0208  Q_PHX1_YR  Q_PHX1_CR  \
0            2002   572493     200211              0.0        NaN        NaN   
1            2002   874800     200207              0.0        NaN        NaN   
2            2002    88450     200207              0.0        NaN        NaN   
3            2002    56993     200212              0.0        NaN        NaN   
4            2002   591264     200210              0.0        NaN        NaN   
...           ...      ...        ...              ...        ...        ...   
1046         2008   218649     200806              1.0     1982.0        1.0   
1047         2008    39217     200812              NaN        NaN        NaN   
1048         2008   756414     200812              NaN        NaN        NaN   
1049         2008   642899     200806              NaN        NaN        NaN   
1050         2008   238542     200806              2.0     1991.0        2.0   

      Q_PHX2_DZ_V0208  Q_PHX2_YR  Q_PHX2_CR  Q_PHX3_DZ_V0208  ...  \
0                 0.0        NaN        NaN              0.0  ...   
1                 0.0        NaN        NaN              0.0  ...   
2                 0.0        NaN        NaN              0.0  ...   
3                 0.0        NaN        NaN              0.0  ...   
4                 0.0        NaN        NaN              0.0  ...   
...               ...        ...        ...              ...  ...   
1046              NaN        NaN        NaN              NaN  ...   
1047              NaN        NaN        NaN              NaN  ...   
1048              NaN        NaN        NaN              NaN  ...   
1049              NaN        NaN        NaN              NaN  ...   
1050              NaN        NaN        NaN              NaN  ...   

      G1E_URN_OCC_BLD  G1E_URN_PH  G1E_HGB  G1E_FBS  G1E_TOT_CHOL  G1E_SGOT  \
0                 1.0         6.0     13.3     75.0           216        26   
1                 1.0         6.0     15.2    108.0           194        27   
2                 1.0         6.0     14.0     81.0           196        22   
3                 1.0         6.0     14.7     89.0           159        12   
4                 1.0         6.0     17.2    104.0           198        33   
...               ...         ...      ...      ...           ...       ...   
1046              1.0         6.0     16.1     84.0           264        31   
1047              1.0         6.0     13.8    225.0           265        38   
1048              1.0         7.0     13.2    117.0           178        88   
1049              1.0         6.0     11.3     68.0           177        49   
1050              1.0         6.5     15.4     84.0           203        84   

      G1E_SGPT  G1E_GGT  G1E_CHST_XRAY_RST G1E_EKG_RST  
0           30     12.0                1.0         NaN  
1           37     21.0                1.0         1.0  
2           17     10.0                1.0         1.0  
3           19     76.0                1.0         NaN  
4           33     34.0                1.0         NaN  
...        ...      ...                ...         ...  
1046        39     75.0                1.0         NaN  
1047        41    146.0                1.0         1.0  
1048       171    126.0                1.0         1.0  
1049        32    154.0                1.0         1.0  
1050        47     74.0                1.0         2.0  

[1051 rows x 51 columns]

- 필요없는 열 없애기

In [155]:
merge_data.drop(["Q_PHX1_YR","Q_PHX2_YR","Q_PHX3_YR",
                 "Q_PHX1_CR","Q_PHX2_CR","Q_PHX3_CR","G1E_EKG_RST","Q_AWR_YN","Q_AWR_DZ",
                 "Q_NTR_PRF","G1E_HGHT","G1E_WGHT","G1E_VA_LT","G1E_VA_RT","G1E_HA_LT","G1E_HA_RT",
                 "G1E_URN_GLU","G1E_URN_OCC_BLD","G1E_URN_PH","G1E_CHST_XRAY_RST","G1E_GGT",
                 "G1E_CHST_XRAY_RST"],axis=1,inplace=True)
merge_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_PHX1_DZ_V0208  Q_PHX2_DZ_V0208  \
0            2002   572493     200211              0.0              0.0   
1            2002   874800     200207              0.0              0.0   
2            2002    88450     200207              0.0              0.0   
3            2002    56993     200212              0.0              0.0   
4            2002   591264     200210              0.0              0.0   
...           ...      ...        ...              ...              ...   
1046         2008   218649     200806              1.0              NaN   
1047         2008    39217     200812              NaN              NaN   
1048         2008   756414     200812              NaN              NaN   
1049         2008   642899     200806              NaN              NaN   
1050         2008   238542     200806              2.0              NaN   

      Q_PHX3_DZ_V0208  Q_FHX_LVDZ  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  ...  \
0                 0.0         1.0        1.0        1.0         1.0  ...   
1                 0.0         1.0        1.0        1.0         1.0  ...   
2                 0.0         1.0        1.0        1.0         1.0  ...   
3                 0.0         NaN        NaN        NaN         NaN  ...   
4                 0.0         1.0        1.0        1.0         1.0  ...   
...               ...         ...        ...        ...         ...  ...   
1046              NaN         1.0        1.0        1.0         1.0  ...   
1047              NaN         1.0        1.0        1.0         1.0  ...   
1048              NaN         1.0        1.0        1.0         1.0  ...   
1049              NaN         1.0        2.0        1.0         1.0  ...   
1050              NaN         1.0        1.0        1.0         1.0  ...   

      G1E_BMI  G1E_WSTC  G1E_BP_SYS  G1E_BP_DIA  G1E_URN_PROT  G1E_HGB  \
0        23.2       NaN         120          80           1.0     13.3   
1        29.4       NaN         120          80           1.0     15.2   
2        23.4       NaN         130          80           1.0     14.0   
3        25.6       NaN         130          80           1.0     14.7   
4        29.7       NaN         130          80           1.0     17.2   
...       ...       ...         ...         ...           ...      ...   
1046     24.3      89.0         120          80           1.0     16.1   
1047     29.8      90.0         140         100           4.0     13.8   
1048     22.7      71.0         137          85           1.0     13.2   
1049     21.6      70.0         108          66           1.0     11.3   
1050     31.6      96.0         115          70           2.0     15.4   

      G1E_FBS  G1E_TOT_CHOL  G1E_SGOT  G1E_SGPT  
0        75.0           216        26        30  
1       108.0           194        27        37  
2        81.0           196        22        17  
3        89.0           159        12        19  
4       104.0           198        33        33  
...       ...           ...       ...       ...  
1046     84.0           264        31        39  
1047    225.0           265        38        41  
1048    117.0           178        88       171  
1049     68.0           177        49        32  
1050     84.0           203        84        47  

[1051 rows x 30 columns]

- 건강검진테이블2과 변수를 통일화 하기(과거 질병병력유무 열 추가)

In [156]:
merge_data["Q_PHX_DX_STK"]=0
merge_data["Q_PHX_DX_HTDZ"]=0
merge_data["Q_PHX_DX_HTN"]=0
merge_data["Q_PHX_DX_DM"]=0
merge_data["Q_PHX_DX_PTB"]=0
merge_data["Q_PHX_DX_ETC"]=0
# merge_data["Q_PHX_TX_STK"]=0
# merge_data["Q_PHX_TX_HTDZ"]=0
# merge_data["Q_PHX_TX_HTN"]=0
# merge_data["Q_PHX_TX_DM"]=0
# merge_data["Q_PHX_TX_STK"]=0
# merge_data["Q_PHX_DX_STK"]=0

In [157]:
merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]] = merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]].fillna(0)
merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]] = merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]].astype("int")

In [158]:
merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]]

Q_PHX1_DZ_V0208  Q_PHX2_DZ_V0208  Q_PHX3_DZ_V0208
0                   0                0                0
1                   0                0                0
2                   0                0                0
3                   0                0                0
4                   0                0                0
...               ...              ...              ...
1046                1                0                0
1047                0                0                0
1048                0                0                0
1049                0                0                0
1050                2                0                0

[1051 rows x 3 columns]

- 과거 병력값에 따라 과거 질병병력유무에 값추가

In [ ]:
for idx, dias_list in merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]].iterrows():
    for dias in dias_list:
        if dias == 1: merge_data["Q_PHX_DX_PTB"][idx] = 1
        elif dias == 4: merge_data["Q_PHX_DX_HTN"][idx] = 1
        elif dias == 5: merge_data["Q_PHX_DX_HTDZ"][idx] = 1
        elif dias == 6: merge_data["Q_PHX_DX_STK"][idx] = 1
        elif dias == 7: merge_data["Q_PHX_DX_DM"][idx]= 1
        elif dias == 8: merge_data["Q_PHX_DX_ETC"][idx] = 1
        elif dias == 9: merge_data["Q_PHX_DX_ETC"][idx] = 1

In [160]:
merge_data[["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"]]

Q_PHX1_DZ_V0208  Q_PHX2_DZ_V0208  Q_PHX3_DZ_V0208
0                   0                0                0
1                   0                0                0
2                   0                0                0
3                   0                0                0
4                   0                0                0
...               ...              ...              ...
1046                1                0                0
1047                0                0                0
1048                0                0                0
1049                0                0                0
1050                2                0                0

[1051 rows x 3 columns]

In [161]:
merge_data[["Q_PHX_DX_PTB","Q_PHX_DX_HTN","Q_PHX_DX_HTDZ","Q_PHX_DX_STK","Q_PHX_DX_DM","Q_PHX_DX_ETC"]]

Q_PHX_DX_PTB  Q_PHX_DX_HTN  Q_PHX_DX_HTDZ  Q_PHX_DX_STK  Q_PHX_DX_DM  \
0                0             0              0             0            0   
1                0             0              0             0            0   
2                0             0              0             0            0   
3                0             0              0             0            0   
4                0             0              0             0            0   
...            ...           ...            ...           ...          ...   
1046             1             0              0             0            0   
1047             0             0              0             0            0   
1048             0             0              0             0            0   
1049             0             0              0             0            0   
1050             0             0              0             0            0   

      Q_PHX_DX_ETC  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
1046             0  
1047             0  
1048             0  
1049             0  
1050             0  

[1051 rows x 6 columns]

- 과거병력코드 1, 2, 3 열 없애기

In [162]:
merge_data.drop(["Q_PHX1_DZ_V0208","Q_PHX2_DZ_V0208","Q_PHX3_DZ_V0208"],axis=1,inplace=True)

In [163]:
merge_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_FHX_LVDZ  Q_FHX_HTN  Q_FHX_STK  \
0            2002   572493     200211         1.0        1.0        1.0   
1            2002   874800     200207         1.0        1.0        1.0   
2            2002    88450     200207         1.0        1.0        1.0   
3            2002    56993     200212         NaN        NaN        NaN   
4            2002   591264     200210         1.0        1.0        1.0   
...           ...      ...        ...         ...        ...        ...   
1046         2008   218649     200806         1.0        1.0        1.0   
1047         2008    39217     200812         1.0        1.0        1.0   
1048         2008   756414     200812         1.0        1.0        1.0   
1049         2008   642899     200806         1.0        2.0        1.0   
1050         2008   238542     200806         1.0        1.0        1.0   

      Q_FHX_HTDZ  Q_FHX_DM  Q_FHX_CC  Q_DRK_FRQ_V0108  ...  G1E_FBS  \
0            1.0       1.0       1.0              1.0  ...     75.0   
1            1.0       1.0       1.0              1.0  ...    108.0   
2            1.0       1.0       2.0              1.0  ...     81.0   
3            NaN       2.0       NaN              2.0  ...     89.0   
4            1.0       1.0       1.0              2.0  ...    104.0   
...          ...       ...       ...              ...  ...      ...   
1046         1.0       1.0       1.0              3.0  ...     84.0   
1047         1.0       2.0       1.0              3.0  ...    225.0   
1048         1.0       1.0       1.0              1.0  ...    117.0   
1049         1.0       1.0       1.0              1.0  ...     68.0   
1050         1.0       1.0       1.0              3.0  ...     84.0   

      G1E_TOT_CHOL  G1E_SGOT  G1E_SGPT  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0              216        26        30             0              0   
1              194        27        37             0              0   
2              196        22        17             0              0   
3              159        12        19             0              0   
4              198        33        33             0              0   
...            ...       ...       ...           ...            ...   
1046           264        31        39             0              0   
1047           265        38        41             0              0   
1048           178        88       171             0              0   
1049           177        49        32             0              0   
1050           203        84        47             0              0   

      Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  
0                0            0             0             0  
1                0            0             0             0  
2                0            0             0             0  
3                0            0             0             0  
4                0            0             0             0  
...            ...          ...           ...           ...  
1046             0            0             1             0  
1047             0            0             0             0  
1048             0            0             0             0  
1049             0            0             0             0  
1050             0            0             0             0  

[1051 rows x 33 columns]

- 가족력관한 열 값 바꾸기
- 1->0 2->1로 바꾸기(건강검진테이블2과 똑같이 하기 위해)

In [164]:
merge_data.drop(["Q_FHX_LVDZ"],axis=1,inplace=True)

In [165]:
merge_data[["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]] =merge_data[["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]].fillna(1)

In [166]:
merge_data[["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]]

Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  Q_FHX_DM  Q_FHX_CC
0           1.0        1.0         1.0       1.0       1.0
1           1.0        1.0         1.0       1.0       1.0
2           1.0        1.0         1.0       1.0       2.0
3           1.0        1.0         1.0       2.0       1.0
4           1.0        1.0         1.0       1.0       1.0
...         ...        ...         ...       ...       ...
1046        1.0        1.0         1.0       1.0       1.0
1047        1.0        1.0         1.0       2.0       1.0
1048        1.0        1.0         1.0       1.0       1.0
1049        2.0        1.0         1.0       1.0       1.0
1050        1.0        1.0         1.0       1.0       1.0

[1051 rows x 5 columns]

In [ ]:
for name in ["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]:
    merge_data[name][merge_data[name] == 1] = 0
    merge_data[name][merge_data[name] == 2] = 1

In [168]:
merge_data[["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]]

Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  Q_FHX_DM  Q_FHX_CC
0           0.0        0.0         0.0       0.0       0.0
1           0.0        0.0         0.0       0.0       0.0
2           0.0        0.0         0.0       0.0       1.0
3           0.0        0.0         0.0       1.0       0.0
4           0.0        0.0         0.0       0.0       0.0
...         ...        ...         ...       ...       ...
1046        0.0        0.0         0.0       0.0       0.0
1047        0.0        0.0         0.0       1.0       0.0
1048        0.0        0.0         0.0       0.0       0.0
1049        1.0        0.0         0.0       0.0       0.0
1050        0.0        0.0         0.0       0.0       0.0

[1051 rows x 5 columns]

In [169]:
merge_data [["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]]=merge_data [["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]].astype("int")

In [170]:
merge_data[["Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_CC"]]

Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  Q_FHX_DM  Q_FHX_CC
0             0          0           0         0         0
1             0          0           0         0         0
2             0          0           0         0         1
3             0          0           0         1         0
4             0          0           0         0         0
...         ...        ...         ...       ...       ...
1046          0          0           0         0         0
1047          0          0           0         1         0
1048          0          0           0         0         0
1049          1          0           0         0         0
1050          0          0           0         0         0

[1051 rows x 5 columns]

- 필요없는 열 다시 제거(전문가 자문으로 생애 질병 확률에는 운동, 술, 담배, 가족력, BMI을 확인하는 것이 중요)

In [171]:
merge_data.columns

Index(['EXMD_BZ_YYYY', 'RN_INDI', 'HME_YYYYMM', 'Q_FHX_HTN', 'Q_FHX_STK',
       'Q_FHX_HTDZ', 'Q_FHX_DM', 'Q_FHX_CC', 'Q_DRK_FRQ_V0108',
       'Q_DRK_AMT_V0108', 'Q_SMK_YN', 'Q_SMK_NOW_AMT_V0108', 'Q_SMK_DRT',
       'Q_SMK_STRT_YR', 'Q_SMK_STOP_YR', 'Q_PA_FRQ', 'G1E_BMI', 'G1E_WSTC',
       'G1E_BP_SYS', 'G1E_BP_DIA', 'G1E_URN_PROT', 'G1E_HGB', 'G1E_FBS',
       'G1E_TOT_CHOL', 'G1E_SGOT', 'G1E_SGPT', 'Q_PHX_DX_STK', 'Q_PHX_DX_HTDZ',
       'Q_PHX_DX_HTN', 'Q_PHX_DX_DM', 'Q_PHX_DX_PTB', 'Q_PHX_DX_ETC'],
      dtype='object')

In [172]:
merge_data.drop(["Q_SMK_STRT_YR","Q_SMK_STOP_YR","Q_SMK_DRT","G1E_WSTC"],axis=1,inplace=True)
merge_data.drop(["G1E_URN_PROT","G1E_HGB","G1E_FBS","G1E_TOT_CHOL","G1E_SGOT","G1E_SGPT"],axis=1,inplace=True)
merge_data.drop(['G1E_BP_SYS', 'G1E_BP_DIA',],axis=1,inplace=True)

In [173]:
merge_data.columns

Index(['EXMD_BZ_YYYY', 'RN_INDI', 'HME_YYYYMM', 'Q_FHX_HTN', 'Q_FHX_STK',
       'Q_FHX_HTDZ', 'Q_FHX_DM', 'Q_FHX_CC', 'Q_DRK_FRQ_V0108',
       'Q_DRK_AMT_V0108', 'Q_SMK_YN', 'Q_SMK_NOW_AMT_V0108', 'Q_PA_FRQ',
       'G1E_BMI', 'Q_PHX_DX_STK', 'Q_PHX_DX_HTDZ', 'Q_PHX_DX_HTN',
       'Q_PHX_DX_DM', 'Q_PHX_DX_PTB', 'Q_PHX_DX_ETC'],
      dtype='object')

In [174]:
merge_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0            2002   572493     200211          0          0           0   
1            2002   874800     200207          0          0           0   
2            2002    88450     200207          0          0           0   
3            2002    56993     200212          0          0           0   
4            2002   591264     200210          0          0           0   
...           ...      ...        ...        ...        ...         ...   
1046         2008   218649     200806          0          0           0   
1047         2008    39217     200812          0          0           0   
1048         2008   756414     200812          0          0           0   
1049         2008   642899     200806          1          0           0   
1050         2008   238542     200806          0          0           0   

      Q_FHX_DM  Q_FHX_CC  Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  Q_SMK_YN  \
0            0         0              1.0              NaN       1.0   
1            0         0              1.0              NaN       1.0   
2            0         1              1.0              NaN       1.0   
3            1         0              2.0              2.0       1.0   
4            0         0              2.0              2.0       3.0   
...        ...       ...              ...              ...       ...   
1046         0         0              3.0              4.0       2.0   
1047         1         0              3.0              3.0       2.0   
1048         0         0              1.0              NaN       1.0   
1049         0         0              1.0              NaN       1.0   
1050         0         0              3.0              1.0       1.0   

      Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0                     NaN       1.0     23.2             0              0   
1                     NaN       2.0     29.4             0              0   
2                     NaN       2.0     23.4             0              0   
3                     NaN       1.0     25.6             0              0   
4                     2.0       1.0     29.7             0              0   
...                   ...       ...      ...           ...            ...   
1046                  NaN       1.0     24.3             0              0   
1047                  NaN       1.0     29.8             0              0   
1048                  NaN       1.0     22.7             0              0   
1049                  NaN       5.0     21.6             0              0   
1050                  NaN       2.0     31.6             0              0   

      Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  
0                0            0             0             0  
1                0            0             0             0  
2                0            0             0             0  
3                0            0             0             0  
4                0            0             0             0  
...            ...          ...           ...           ...  
1046             0            0             1             0  
1047             0            0             0             0  
1048             0            0             0             0  
1049             0            0             0             0  
1050             0            0             0             0  

[1051 rows x 20 columns]

In [175]:
merge_data[["Q_DRK_FRQ_V0108","Q_DRK_AMT_V0108","Q_SMK_YN","Q_SMK_NOW_AMT_V0108","Q_PA_FRQ"]]

Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  Q_SMK_YN  Q_SMK_NOW_AMT_V0108  \
0                 1.0              NaN       1.0                  NaN   
1                 1.0              NaN       1.0                  NaN   
2                 1.0              NaN       1.0                  NaN   
3                 2.0              2.0       1.0                  NaN   
4                 2.0              2.0       3.0                  2.0   
...               ...              ...       ...                  ...   
1046              3.0              4.0       2.0                  NaN   
1047              3.0              3.0       2.0                  NaN   
1048              1.0              NaN       1.0                  NaN   
1049              1.0              NaN       1.0                  NaN   
1050              3.0              1.0       1.0                  NaN   

      Q_PA_FRQ  
0          1.0  
1          2.0  
2          2.0  
3          1.0  
4          1.0  
...        ...  
1046       1.0  
1047       1.0  
1048       1.0  
1049       5.0  
1050       2.0  

[1051 rows x 5 columns]

- null 제거

In [176]:
merge_data.isnull().sum()

EXMD_BZ_YYYY             0
RN_INDI                  0
HME_YYYYMM               0
Q_FHX_HTN                0
Q_FHX_STK                0
Q_FHX_HTDZ               0
Q_FHX_DM                 0
Q_FHX_CC                 0
Q_DRK_FRQ_V0108         39
Q_DRK_AMT_V0108        486
Q_SMK_YN                46
Q_SMK_NOW_AMT_V0108    791
Q_PA_FRQ                38
G1E_BMI                  0
Q_PHX_DX_STK             0
Q_PHX_DX_HTDZ            0
Q_PHX_DX_HTN             0
Q_PHX_DX_DM              0
Q_PHX_DX_PTB             0
Q_PHX_DX_ETC             0
dtype: int64

In [177]:
merge_data["Q_DRK_FRQ_V0108"][merge_data["Q_DRK_FRQ_V0108"].isnull()]


46    NaN
68    NaN
76    NaN
115   NaN
124   NaN
132   NaN
188   NaN
191   NaN
380   NaN
512   NaN
542   NaN
569   NaN
589   NaN
594   NaN
597   NaN
636   NaN
695   NaN
724   NaN
725   NaN
726   NaN
738   NaN
758   NaN
759   NaN
875   NaN
901   NaN
905   NaN
918   NaN
919   NaN
921   NaN
924   NaN
927   NaN
931   NaN
934   NaN
936   NaN
938   NaN
958   NaN
962   NaN
963   NaN
966   NaN
Name: Q_DRK_FRQ_V0108, dtype: float64

In [178]:
merge_data["Q_DRK_FRQ_V0108"]=merge_data["Q_DRK_FRQ_V0108"].fillna(int(mode(merge_data["Q_DRK_FRQ_V0108"],nan_policy="omit")[0]))

In [ ]:
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==1] = merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==1].fillna(int(mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==1],nan_policy="omit")[0]))
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==2] = merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==2].fillna(int(mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==2],nan_policy="omit")[0]))
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==3] = merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==3].fillna(int(mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==3],nan_policy="omit")[0]))
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==4] = merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==4].fillna(int(mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==4],nan_policy="omit")[0]))
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==5] = merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==5].fillna(int(mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==5],nan_policy="omit")[0]))


In [180]:
mode(merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_FRQ_V0108"]==5],nan_policy="omit")

ModeResult(mode=array([1.]), count=array([9]))

In [ ]:
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_AMT_V0108"]==0]=1

In [182]:
merge_data["Q_DRK_FRQ_V0108"][46]

1.0

In [183]:
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_DRK_AMT_V0108"].isnull()]

Series([], Name: Q_DRK_AMT_V0108, dtype: float64)

In [184]:
merge_data["Q_SMK_YN"]=merge_data["Q_SMK_YN"].fillna(int(mode(merge_data["Q_SMK_YN"],nan_policy="omit")[0]))

In [ ]:
merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==1]=merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==1].fillna(int(mode(merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==1],nan_policy="omit")[0]))
merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==2]=merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==2].fillna(int(mode(merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==2],nan_policy="omit")[0]))
merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==3]=merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==3].fillna(int(mode(merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==3],nan_policy="omit")[0]))

In [ ]:
merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==1]=0
merge_data["Q_SMK_NOW_AMT_V0108"][merge_data["Q_SMK_YN"]==2]=0

In [187]:
merge_data["Q_PA_FRQ"]=merge_data["Q_PA_FRQ"].fillna(int(mode(merge_data["Q_PA_FRQ"],nan_policy="omit")[0]))

In [188]:
merge_data.isnull().sum()

EXMD_BZ_YYYY           0
RN_INDI                0
HME_YYYYMM             0
Q_FHX_HTN              0
Q_FHX_STK              0
Q_FHX_HTDZ             0
Q_FHX_DM               0
Q_FHX_CC               0
Q_DRK_FRQ_V0108        0
Q_DRK_AMT_V0108        0
Q_SMK_YN               0
Q_SMK_NOW_AMT_V0108    0
Q_PA_FRQ               0
G1E_BMI                0
Q_PHX_DX_STK           0
Q_PHX_DX_HTDZ          0
Q_PHX_DX_HTN           0
Q_PHX_DX_DM            0
Q_PHX_DX_PTB           0
Q_PHX_DX_ETC           0
dtype: int64

In [189]:
merge_data[["Q_SMK_YN","Q_SMK_NOW_AMT_V0108","Q_PA_FRQ","Q_DRK_AMT_V0108","Q_DRK_FRQ_V0108"]]

Q_SMK_YN  Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  Q_DRK_AMT_V0108  \
0          1.0                  0.0       1.0              1.0   
1          1.0                  0.0       2.0              1.0   
2          1.0                  0.0       2.0              1.0   
3          1.0                  0.0       1.0              2.0   
4          3.0                  2.0       1.0              2.0   
...        ...                  ...       ...              ...   
1046       2.0                  0.0       1.0              4.0   
1047       2.0                  0.0       1.0              3.0   
1048       1.0                  0.0       1.0              1.0   
1049       1.0                  0.0       5.0              1.0   
1050       1.0                  0.0       2.0              1.0   

      Q_DRK_FRQ_V0108  
0                 1.0  
1                 1.0  
2                 1.0  
3                 2.0  
4                 2.0  
...               ...  
1046              3.0  
1047              3.0  
1048              1.0  
1049              1.0  
1050              3.0  

[1051 rows x 5 columns]

In [190]:
merge_data["Q_SMK_YN"]=merge_data["Q_SMK_YN"].astype("int")
merge_data["Q_SMK_NOW_AMT_V0108"]=merge_data["Q_SMK_NOW_AMT_V0108"].astype("int")
merge_data["Q_PA_FRQ"]=merge_data["Q_PA_FRQ"].astype("int")
merge_data["Q_DRK_AMT_V0108"]=merge_data["Q_DRK_AMT_V0108"].astype("int")
merge_data["Q_DRK_FRQ_V0108"]=merge_data["Q_DRK_FRQ_V0108"].astype("int")

In [191]:
merge_data["Q_DRK_AMT_V0108"][merge_data["Q_SMK_YN"]==1]

0       1
1       1
2       1
3       2
7       1
       ..
1044    1
1045    1
1048    1
1049    1
1050    1
Name: Q_DRK_AMT_V0108, Length: 663, dtype: int32

In [192]:
merge_data[["Q_SMK_YN","Q_SMK_NOW_AMT_V0108","Q_PA_FRQ","Q_DRK_AMT_V0108","Q_DRK_FRQ_V0108"]]

Q_SMK_YN  Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  Q_DRK_AMT_V0108  \
0            1                    0         1                1   
1            1                    0         2                1   
2            1                    0         2                1   
3            1                    0         1                2   
4            3                    2         1                2   
...        ...                  ...       ...              ...   
1046         2                    0         1                4   
1047         2                    0         1                3   
1048         1                    0         1                1   
1049         1                    0         5                1   
1050         1                    0         2                1   

      Q_DRK_FRQ_V0108  
0                   1  
1                   1  
2                   1  
3                   2  
4                   2  
...               ...  
1046                3  
1047                3  
1048                1  
1049                1  
1050                3  

[1051 rows x 5 columns]

In [193]:
merge_data.columns

Index(['EXMD_BZ_YYYY', 'RN_INDI', 'HME_YYYYMM', 'Q_FHX_HTN', 'Q_FHX_STK',
       'Q_FHX_HTDZ', 'Q_FHX_DM', 'Q_FHX_CC', 'Q_DRK_FRQ_V0108',
       'Q_DRK_AMT_V0108', 'Q_SMK_YN', 'Q_SMK_NOW_AMT_V0108', 'Q_PA_FRQ',
       'G1E_BMI', 'Q_PHX_DX_STK', 'Q_PHX_DX_HTDZ', 'Q_PHX_DX_HTN',
       'Q_PHX_DX_DM', 'Q_PHX_DX_PTB', 'Q_PHX_DX_ETC'],
      dtype='object')

In [194]:
merge_data["G1E_BMI"][:20]

0     23.2
1     29.4
2     23.4
3     25.6
4     29.7
5     25.1
6     25.5
7     22.4
8     22.2
9     20.6
10    19.5
11    25.8
12    22.5
13    19.8
14    23.8
15    22.0
16    24.8
17    24.8
18    24.7
19    29.4
Name: G1E_BMI, dtype: float64

In [ ]:
merge_data["G1E_BMI"][merge_data["G1E_BMI"]<= 18.5] = 0
merge_data["G1E_BMI"][(merge_data["G1E_BMI"]<= 25.0) & (merge_data["G1E_BMI"]>18.5)] = 1
merge_data["G1E_BMI"][(merge_data["G1E_BMI"]<= 30.0) & (merge_data["G1E_BMI"]>25.0)] = 2
merge_data["G1E_BMI"][merge_data["G1E_BMI"]> 30.0] = 3

In [196]:
merge_data["G1E_BMI"]=merge_data["G1E_BMI"].astype("int")

In [197]:
merge_data["G1E_BMI"]

0       1
1       2
2       1
3       2
4       2
       ..
1046    1
1047    2
1048    1
1049    1
1050    3
Name: G1E_BMI, Length: 1051, dtype: int32

In [198]:
merge_data.rename(columns={'Q_FHX_CC':'Q_FHX_ETC'},inplace=True)

In [199]:
merge_data.columns

Index(['EXMD_BZ_YYYY', 'RN_INDI', 'HME_YYYYMM', 'Q_FHX_HTN', 'Q_FHX_STK',
       'Q_FHX_HTDZ', 'Q_FHX_DM', 'Q_FHX_ETC', 'Q_DRK_FRQ_V0108',
       'Q_DRK_AMT_V0108', 'Q_SMK_YN', 'Q_SMK_NOW_AMT_V0108', 'Q_PA_FRQ',
       'G1E_BMI', 'Q_PHX_DX_STK', 'Q_PHX_DX_HTDZ', 'Q_PHX_DX_HTN',
       'Q_PHX_DX_DM', 'Q_PHX_DX_PTB', 'Q_PHX_DX_ETC'],
      dtype='object')

- 건강검진테이블2 전처리

In [200]:
modify_screening2_data=modify_screening2_data[["EXMD_BZ_YYYY","RN_INDI","HME_YYYYMM","Q_FHX_HTN","Q_FHX_STK","Q_FHX_HTDZ","Q_FHX_DM","Q_FHX_ETC",
                 "Q_SMK_YN","Q_SMK_NOW_AMT_V09N","Q_DRK_FRQ_V09N","Q_DRK_AMT_V09N",
                 "Q_PA_VD","Q_PA_MD","Q_PA_WALK","G1E_BMI","Q_PHX_DX_STK","Q_PHX_DX_HTDZ","Q_PHX_DX_HTN","Q_PHX_DX_DM","Q_PHX_DX_PTB","Q_PHX_DX_ETC"]]

In [201]:
len(modify_screening2_data)

1644

In [202]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY             0
RN_INDI                  0
HME_YYYYMM               0
Q_FHX_HTN              515
Q_FHX_STK              556
Q_FHX_HTDZ             553
Q_FHX_DM               534
Q_FHX_ETC              530
Q_SMK_YN                 2
Q_SMK_NOW_AMT_V09N    1257
Q_DRK_FRQ_V09N           6
Q_DRK_AMT_V09N         643
Q_PA_VD                  4
Q_PA_MD                  3
Q_PA_WALK                4
G1E_BMI                  0
Q_PHX_DX_STK           573
Q_PHX_DX_HTDZ          566
Q_PHX_DX_HTN           492
Q_PHX_DX_DM            547
Q_PHX_DX_PTB           703
Q_PHX_DX_ETC           560
dtype: int64

In [203]:
len(modify_screening2_data.columns)

22

- 흡연 관련결측치 제거

In [204]:
modify_screening2_data["Q_FHX_HTN"] = modify_screening2_data["Q_FHX_HTN"].fillna(0)
modify_screening2_data["Q_FHX_STK"] = modify_screening2_data["Q_FHX_STK"].fillna(0)
modify_screening2_data["Q_FHX_HTDZ"] = modify_screening2_data["Q_FHX_HTDZ"].fillna(0)
modify_screening2_data["Q_FHX_DM"] = modify_screening2_data["Q_FHX_DM"].fillna(0)
modify_screening2_data["Q_FHX_ETC"] = modify_screening2_data["Q_FHX_ETC"].fillna(0)

In [205]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY             0
RN_INDI                  0
HME_YYYYMM               0
Q_FHX_HTN                0
Q_FHX_STK                0
Q_FHX_HTDZ               0
Q_FHX_DM                 0
Q_FHX_ETC                0
Q_SMK_YN                 2
Q_SMK_NOW_AMT_V09N    1257
Q_DRK_FRQ_V09N           6
Q_DRK_AMT_V09N         643
Q_PA_VD                  4
Q_PA_MD                  3
Q_PA_WALK                4
G1E_BMI                  0
Q_PHX_DX_STK           573
Q_PHX_DX_HTDZ          566
Q_PHX_DX_HTN           492
Q_PHX_DX_DM            547
Q_PHX_DX_PTB           703
Q_PHX_DX_ETC           560
dtype: int64

In [206]:
modify_screening2_data[["Q_SMK_YN","Q_SMK_NOW_AMT_V09N"]][modify_screening2_data["Q_SMK_YN"].isnull()]

Q_SMK_YN  Q_SMK_NOW_AMT_V09N
95        NaN                 NaN
112       NaN                 NaN

In [207]:
modify_screening2_data["Q_SMK_YN"]

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
1639    2.0
1640    2.0
1641    2.0
1642    2.0
1643    2.0
Name: Q_SMK_YN, Length: 1644, dtype: float64

In [208]:
modify_screening2_data["Q_SMK_YN"].value_counts()

1.0    995
3.0    391
2.0    256
Name: Q_SMK_YN, dtype: int64

In [209]:
modify_screening2_data["Q_SMK_YN"]=modify_screening2_data["Q_SMK_YN"].fillna(int(mode(modify_screening2_data["Q_SMK_YN"],nan_policy="omit")[0]))

In [210]:
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][(modify_screening2_data["Q_SMK_YN"]==3)&(modify_screening2_data["Q_SMK_NOW_AMT_V09N"].isnull())]

140   NaN
165   NaN
376   NaN
571   NaN
Name: Q_SMK_NOW_AMT_V09N, dtype: float64

In [211]:
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][modify_screening2_data["Q_SMK_YN"]==1] = 0
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][modify_screening2_data["Q_SMK_YN"]==2] = 0

C:\Users\tlsgh\anaconda3\envs\osaesg\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\tlsgh\anaconda3\envs\osaesg\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [212]:
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][(modify_screening2_data["Q_SMK_YN"]==3)&(modify_screening2_data["Q_SMK_NOW_AMT_V09N"].isnull())] = 10.0

C:\Users\tlsgh\anaconda3\envs\osaesg\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [213]:
set(modify_screening2_data["Q_SMK_NOW_AMT_V09N"])

{0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 15.0,
 17.0,
 18.0,
 20.0,
 22.0,
 25.0,
 30.0,
 35.0,
 37.0,
 40.0,
 50.0}

In [214]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY            0
RN_INDI                 0
HME_YYYYMM              0
Q_FHX_HTN               0
Q_FHX_STK               0
Q_FHX_HTDZ              0
Q_FHX_DM                0
Q_FHX_ETC               0
Q_SMK_YN                0
Q_SMK_NOW_AMT_V09N      0
Q_DRK_FRQ_V09N          6
Q_DRK_AMT_V09N        643
Q_PA_VD                 4
Q_PA_MD                 3
Q_PA_WALK               4
G1E_BMI                 0
Q_PHX_DX_STK          573
Q_PHX_DX_HTDZ         566
Q_PHX_DX_HTN          492
Q_PHX_DX_DM           547
Q_PHX_DX_PTB          703
Q_PHX_DX_ETC          560
dtype: int64

- 음주 관련결측치 제거

In [215]:
modify_screening2_data["Q_DRK_FRQ_V09N"]=modify_screening2_data["Q_DRK_FRQ_V09N"].fillna(int(mode(modify_screening2_data["Q_DRK_FRQ_V09N"],nan_policy="omit")[0]))

In [ ]:
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==0]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==0].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==0],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==1]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==1].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==1],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==2]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==2].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==2],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==3]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==3].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==3],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==4]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==4].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==4],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==5]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==5].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==5],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==6]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==6].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==6],nan_policy="omit")[0]))
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==7]=modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==7].fillna(int(mode(modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_FRQ_V09N"]==7],nan_policy="omit")[0]))

In [217]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY            0
RN_INDI                 0
HME_YYYYMM              0
Q_FHX_HTN               0
Q_FHX_STK               0
Q_FHX_HTDZ              0
Q_FHX_DM                0
Q_FHX_ETC               0
Q_SMK_YN                0
Q_SMK_NOW_AMT_V09N      0
Q_DRK_FRQ_V09N          0
Q_DRK_AMT_V09N          0
Q_PA_VD                 4
Q_PA_MD                 3
Q_PA_WALK               4
G1E_BMI                 0
Q_PHX_DX_STK          573
Q_PHX_DX_HTDZ         566
Q_PHX_DX_HTN          492
Q_PHX_DX_DM           547
Q_PHX_DX_PTB          703
Q_PHX_DX_ETC          560
dtype: int64

- 운동 전처리

In [218]:
modify_screening2_data["Q_PA_VD"]=modify_screening2_data["Q_PA_VD"].fillna(int(mode(modify_screening2_data["Q_PA_VD"],nan_policy="omit")[0]))
modify_screening2_data["Q_PA_MD"]=modify_screening2_data["Q_PA_MD"].fillna(int(mode(modify_screening2_data["Q_PA_MD"],nan_policy="omit")[0]))
modify_screening2_data["Q_PA_WALK"]=modify_screening2_data["Q_PA_WALK"].fillna(int(mode(modify_screening2_data["Q_PA_WALK"],nan_policy="omit")[0]))

In [219]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY            0
RN_INDI                 0
HME_YYYYMM              0
Q_FHX_HTN               0
Q_FHX_STK               0
Q_FHX_HTDZ              0
Q_FHX_DM                0
Q_FHX_ETC               0
Q_SMK_YN                0
Q_SMK_NOW_AMT_V09N      0
Q_DRK_FRQ_V09N          0
Q_DRK_AMT_V09N          0
Q_PA_VD                 0
Q_PA_MD                 0
Q_PA_WALK               0
G1E_BMI                 0
Q_PHX_DX_STK          573
Q_PHX_DX_HTDZ         566
Q_PHX_DX_HTN          492
Q_PHX_DX_DM           547
Q_PHX_DX_PTB          703
Q_PHX_DX_ETC          560
dtype: int64

In [220]:
modify_screening2_data["Q_PHX_DX_STK"]=modify_screening2_data["Q_PHX_DX_STK"].fillna(0)
modify_screening2_data["Q_PHX_DX_HTDZ"]=modify_screening2_data["Q_PHX_DX_HTDZ"].fillna(0)
modify_screening2_data["Q_PHX_DX_HTN"]=modify_screening2_data["Q_PHX_DX_HTN"].fillna(0)
modify_screening2_data["Q_PHX_DX_DM"]=modify_screening2_data["Q_PHX_DX_DM"].fillna(0)
modify_screening2_data["Q_PHX_DX_PTB"]=modify_screening2_data["Q_PHX_DX_PTB"].fillna(0)
modify_screening2_data["Q_PHX_DX_ETC"]=modify_screening2_data["Q_PHX_DX_ETC"].fillna(0)

In [221]:
modify_screening2_data.isnull().sum()

EXMD_BZ_YYYY          0
RN_INDI               0
HME_YYYYMM            0
Q_FHX_HTN             0
Q_FHX_STK             0
Q_FHX_HTDZ            0
Q_FHX_DM              0
Q_FHX_ETC             0
Q_SMK_YN              0
Q_SMK_NOW_AMT_V09N    0
Q_DRK_FRQ_V09N        0
Q_DRK_AMT_V09N        0
Q_PA_VD               0
Q_PA_MD               0
Q_PA_WALK             0
G1E_BMI               0
Q_PHX_DX_STK          0
Q_PHX_DX_HTDZ         0
Q_PHX_DX_HTN          0
Q_PHX_DX_DM           0
Q_PHX_DX_PTB          0
Q_PHX_DX_ETC          0
dtype: int64

- 운동 횟수 건강검지1이랑 값 맞추기

In [222]:
modify_screening2_data[["Q_PA_MD","Q_PA_VD","Q_PA_WALK"]]

Q_PA_MD  Q_PA_VD  Q_PA_WALK
0         0.0      0.0        0.0
1         0.0      0.0        0.0
2         0.0      0.0        0.0
3         0.0      0.0        0.0
4         0.0      0.0        0.0
...       ...      ...        ...
1639      2.0      2.0        2.0
1640      1.0      1.0        1.0
1641      0.0      0.0        0.0
1642      2.0      3.0        2.0
1643      0.0      0.0        5.0

[1644 rows x 3 columns]

In [223]:
modify_screening2_data["Q_PA_MD"]+modify_screening2_data["Q_PA_VD"]+modify_screening2_data["Q_PA_WALK"]

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1639    6.0
1640    3.0
1641    0.0
1642    7.0
1643    5.0
Length: 1644, dtype: float64

In [224]:
modify_screening2_data["Q_PA_FRQ"]=modify_screening2_data["Q_PA_MD"]+modify_screening2_data["Q_PA_VD"]+modify_screening2_data["Q_PA_WALK"]

In [225]:
modify_screening2_data["Q_PA_FRQ"] = modify_screening2_data["Q_PA_FRQ"].astype("int")

In [ ]:
for idx, freq in enumerate(modify_screening2_data["Q_PA_FRQ"]):
    if freq == 0:modify_screening2_data["Q_PA_FRQ"][idx] = 1
    elif freq == 1:modify_screening2_data["Q_PA_FRQ"][idx] = 2
    elif freq == 2:modify_screening2_data["Q_PA_FRQ"][idx] = 2
    elif freq == 3:modify_screening2_data["Q_PA_FRQ"][idx] = 3
    elif freq == 4:modify_screening2_data["Q_PA_FRQ"][idx] = 3
    elif freq == 5:modify_screening2_data["Q_PA_FRQ"][idx] = 4
    elif freq == 6:modify_screening2_data["Q_PA_FRQ"][idx] = 4
    elif freq >= 7:modify_screening2_data["Q_PA_FRQ"][idx] = 5

In [227]:
modify_screening2_data["Q_PA_FRQ"]

0       1
1       1
2       1
3       1
4       1
       ..
1639    4
1640    3
1641    1
1642    5
1643    4
Name: Q_PA_FRQ, Length: 1644, dtype: int32

In [228]:
modify_screening2_data.drop(["Q_PA_VD","Q_PA_MD","Q_PA_WALK"],axis=1,inplace=True)

In [229]:
modify_screening2_data

EXMD_BZ_YYYY  RN_INDI HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0            2009   562083     200909        1.0        0.0         0.0   
1            2009   334536     200911        0.0        0.0         0.0   
2            2009   911867     200903        0.0        0.0         0.0   
3            2009   183321     200908        0.0        0.0         0.0   
4            2009   942671     200909        0.0        0.0         0.0   
...           ...      ...        ...        ...        ...         ...   
1639         2015   266734     201504        0.0        0.0         0.0   
1640         2015   343874     201511        0.0        0.0         0.0   
1641         2015   798472     201507        0.0        0.0         0.0   
1642         2015   720080     201505        0.0        0.0         0.0   
1643         2015   127519     201511        0.0        0.0         0.0   

      Q_FHX_DM  Q_FHX_ETC  Q_SMK_YN  Q_SMK_NOW_AMT_V09N  Q_DRK_FRQ_V09N  \
0          0.0        0.0       1.0                 0.0             0.0   
1          0.0        0.0       1.0                 0.0             0.0   
2          0.0        0.0       1.0                 0.0             0.0   
3          0.0        0.0       1.0                 0.0             0.0   
4          0.0        0.0       1.0                 0.0             0.0   
...        ...        ...       ...                 ...             ...   
1639       0.0        1.0       2.0                 0.0             2.0   
1640       0.0        0.0       2.0                 0.0             0.0   
1641       0.0        0.0       2.0                 0.0             0.0   
1642       1.0        0.0       2.0                 0.0             1.0   
1643       0.0        0.0       2.0                 0.0             4.0   

      Q_DRK_AMT_V09N  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  Q_PHX_DX_HTN  \
0                0.0     29.4           0.0            0.0           1.0   
1                0.0     19.4           0.0            0.0           0.0   
2                0.0     24.5           0.0            0.0           0.0   
3                0.0     22.1           0.0            0.0           0.0   
4                0.0     19.8           0.0            0.0           0.0   
...              ...      ...           ...            ...           ...   
1639            10.0     26.0           0.0            0.0           0.0   
1640             0.0     25.0           0.0            0.0           0.0   
1641             0.0     23.7           0.0            0.0           0.0   
1642             7.0     25.7           0.0            0.0           0.0   
1643            14.0     29.8           0.0            0.0           1.0   

      Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  Q_PA_FRQ  
0             0.0           0.0           0.0         1  
1             0.0           0.0           0.0         1  
2             0.0           0.0           0.0         1  
3             0.0           0.0           0.0         1  
4             0.0           0.0           0.0         1  
...           ...           ...           ...       ...  
1639          0.0           0.0           0.0         4  
1640          1.0           0.0           0.0         3  
1641          0.0           0.0           0.0         1  
1642          0.0           0.0           0.0         5  
1643          0.0           0.0           0.0         4  

[1644 rows x 20 columns]

- bmi 건강검진1이랑 값 맞추기

In [ ]:
modify_screening2_data["G1E_BMI"][modify_screening2_data["G1E_BMI"]<= 18.5] = 0
modify_screening2_data["G1E_BMI"][(modify_screening2_data["G1E_BMI"]<= 25.0) & (modify_screening2_data["G1E_BMI"]>18.5)] = 1
modify_screening2_data["G1E_BMI"][(modify_screening2_data["G1E_BMI"]<= 30.0) & (modify_screening2_data["G1E_BMI"]>25.0)] = 2
modify_screening2_data["G1E_BMI"][modify_screening2_data["G1E_BMI"]> 30.0] = 3

In [231]:
modify_screening2_data["G1E_BMI"]

0       2.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
1639    2.0
1640    1.0
1641    1.0
1642    2.0
1643    2.0
Name: G1E_BMI, Length: 1644, dtype: float64

In [232]:
modify_screening2_data["G1E_BMI"] =modify_screening2_data["G1E_BMI"].astype("int")

- 흡연관련 데이터 건강검진1이랑 값 맞추기

In [233]:
set(modify_screening2_data["Q_SMK_NOW_AMT_V09N"])

{0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 15.0,
 17.0,
 18.0,
 20.0,
 22.0,
 25.0,
 30.0,
 35.0,
 37.0,
 40.0,
 50.0}

In [ ]:
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]>=1)&(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]<10)] = 1
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]>=10)&(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]<20)] = 2
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]>=20)&(modify_screening2_data["Q_SMK_NOW_AMT_V09N"]<40)] = 3
modify_screening2_data["Q_SMK_NOW_AMT_V09N"][modify_screening2_data["Q_SMK_NOW_AMT_V09N"]>= 40.0] = 4

- 음주관련 데이터 건강검진1과 맞추기

In [235]:
modify_screening2_data["Q_DRK_AMT_V09N"].value_counts()

0.0     759
7.0     130
3.0     127
10.0    123
2.0     102
5.0      88
1.0      84
4.0      70
6.0      41
8.0      38
14.0     23
20.0     17
15.0     14
12.0      8
16.0      8
30.0      3
13.0      3
9.0       2
21.0      1
24.0      1
27.0      1
17.0      1
Name: Q_DRK_AMT_V09N, dtype: int64

In [ ]:
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_AMT_V09N"]<=4]=1
modify_screening2_data["Q_DRK_AMT_V09N"][(modify_screening2_data["Q_DRK_AMT_V09N"]>4)&(modify_screening2_data["Q_DRK_AMT_V09N"]<=7)]=2
modify_screening2_data["Q_DRK_AMT_V09N"][(modify_screening2_data["Q_DRK_AMT_V09N"]>7)&(modify_screening2_data["Q_DRK_AMT_V09N"]<=11)]=3
modify_screening2_data["Q_DRK_AMT_V09N"][modify_screening2_data["Q_DRK_AMT_V09N"]>11]=4

In [237]:
modify_screening2_data["Q_DRK_AMT_V09N"] = modify_screening2_data["Q_DRK_AMT_V09N"].astype("int")

In [ ]:
for idx, freq in enumerate(modify_screening2_data["Q_DRK_FRQ_V09N"]):
    if freq == 0:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 1
    elif freq == 1:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 1
    elif freq == 2:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 2
    elif freq == 3:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 4
    elif freq == 4:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 4
    elif freq == 5:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 5
    elif freq == 6:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 5
    elif freq >= 7:modify_screening2_data["Q_DRK_FRQ_V09N"][idx] = 5

- 건강검진1에 맞게 변수명 바꾸기

In [239]:
modify_screening2_data.rename(columns={"Q_SMK_NOW_AMT_V09N":"Q_SMK_NOW_AMT_V0108","Q_DRK_FRQ_V09N":"Q_DRK_FRQ_V0108","Q_DRK_AMT_V09N":"Q_DRK_AMT_V0108"},inplace=True)

In [240]:
for col,item in modify_screening2_data.iteritems():
    print(col)
print('\n')
for col,item in merge_data.iteritems():
    print(col)

EXMD_BZ_YYYY
RN_INDI
HME_YYYYMM
Q_FHX_HTN
Q_FHX_STK
Q_FHX_HTDZ
Q_FHX_DM
Q_FHX_ETC
Q_SMK_YN
Q_SMK_NOW_AMT_V0108
Q_DRK_FRQ_V0108
Q_DRK_AMT_V0108
G1E_BMI
Q_PHX_DX_STK
Q_PHX_DX_HTDZ
Q_PHX_DX_HTN
Q_PHX_DX_DM
Q_PHX_DX_PTB
Q_PHX_DX_ETC
Q_PA_FRQ


EXMD_BZ_YYYY
RN_INDI
HME_YYYYMM
Q_FHX_HTN
Q_FHX_STK
Q_FHX_HTDZ
Q_FHX_DM
Q_FHX_ETC
Q_DRK_FRQ_V0108
Q_DRK_AMT_V0108
Q_SMK_YN
Q_SMK_NOW_AMT_V0108
Q_PA_FRQ
G1E_BMI
Q_PHX_DX_STK
Q_PHX_DX_HTDZ
Q_PHX_DX_HTN
Q_PHX_DX_DM
Q_PHX_DX_PTB
Q_PHX_DX_ETC


In [241]:
merge_data = merge_data.astype("int")

In [242]:
modify_screening2_data = modify_screening2_data.astype("int")

In [243]:
for col,item in modify_screening2_data.iteritems():
    print(col)
    print(set(item))

for col,item in merge_data.iteritems():
    print(col)
    print(set(item))

EXMD_BZ_YYYY
{2009, 2010, 2011, 2012, 2013, 2014, 2015}
RN_INDI
{294913, 829452, 145424, 964637, 587805, 665633, 495650, 92198, 706602, 825387, 215084, 370738, 38967, 301124, 680010, 335948, 815191, 245849, 606303, 305256, 354421, 725112, 628858, 942204, 909438, 166015, 741504, 739454, 297087, 383109, 948365, 483473, 979090, 237719, 26776, 403607, 92313, 321692, 473250, 4263, 688302, 948405, 336055, 637115, 446652, 764100, 356551, 393421, 727245, 979151, 626896, 839897, 483546, 2270, 346335, 698594, 897251, 96484, 6374, 889062, 884968, 637160, 149741, 194801, 674034, 51442, 768249, 153851, 874754, 663811, 753924, 219397, 559370, 999693, 47374, 762129, 915731, 975124, 334101, 860440, 882980, 870692, 422180, 397613, 874800, 39217, 262452, 559420, 848190, 452930, 921924, 553285, 444740, 418137, 364892, 41309, 84322, 606567, 80234, 934252, 483693, 88450, 344450, 416133, 637320, 717196, 688532, 45461, 911766, 285079, 321944, 582044, 979358, 518558, 49567, 686497, 760226, 532905, 166324, 264

In [244]:
len(modify_screening2_data.columns)

20

In [245]:
merge_data = pd.concat([merge_data, modify_screening2_data])

In [246]:
merge_data

EXMD_BZ_YYYY  RN_INDI  HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0             2002   572493      200211          0          0           0   
1             2002   874800      200207          0          0           0   
2             2002    88450      200207          0          0           0   
3             2002    56993      200212          0          0           0   
4             2002   591264      200210          0          0           0   
...            ...      ...         ...        ...        ...         ...   
1639          2015   266734      201504          0          0           0   
1640          2015   343874      201511          0          0           0   
1641          2015   798472      201507          0          0           0   
1642          2015   720080      201505          0          0           0   
1643          2015   127519      201511          0          0           0   

      Q_FHX_DM  Q_FHX_ETC  Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  Q_SMK_YN  \
0            0          0                1                1         1   
1            0          0                1                1         1   
2            0          1                1                1         1   
3            1          0                2                2         1   
4            0          0                2                2         3   
...        ...        ...              ...              ...       ...   
1639         0          1                2                3         2   
1640         0          0                1                1         2   
1641         0          0                1                1         2   
1642         1          0                1                2         2   
1643         0          0                4                4         2   

      Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0                       0         1        1             0              0   
1                       0         2        2             0              0   
2                       0         2        1             0              0   
3                       0         1        2             0              0   
4                       2         1        2             0              0   
...                   ...       ...      ...           ...            ...   
1639                    0         4        2             0              0   
1640                    0         3        1             0              0   
1641                    0         1        1             0              0   
1642                    0         5        2             0              0   
1643                    0         4        2             0              0   

      Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  
0                0            0             0             0  
1                0            0             0             0  
2                0            0             0             0  
3                0            0             0             0  
4                0            0             0             0  
...            ...          ...           ...           ...  
1639             0            0             0             0  
1640             0            1             0             0  
1641             0            0             0             0  
1642             0            0             0             0  
1643             1            0             0             0  

[2695 rows x 20 columns]

In [247]:
merge_data.reset_index(inplace=True,drop=True)

In [248]:
merge_data

EXMD_BZ_YYYY  RN_INDI  HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0             2002   572493      200211          0          0           0   
1             2002   874800      200207          0          0           0   
2             2002    88450      200207          0          0           0   
3             2002    56993      200212          0          0           0   
4             2002   591264      200210          0          0           0   
...            ...      ...         ...        ...        ...         ...   
2690          2015   266734      201504          0          0           0   
2691          2015   343874      201511          0          0           0   
2692          2015   798472      201507          0          0           0   
2693          2015   720080      201505          0          0           0   
2694          2015   127519      201511          0          0           0   

      Q_FHX_DM  Q_FHX_ETC  Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  Q_SMK_YN  \
0            0          0                1                1         1   
1            0          0                1                1         1   
2            0          1                1                1         1   
3            1          0                2                2         1   
4            0          0                2                2         3   
...        ...        ...              ...              ...       ...   
2690         0          1                2                3         2   
2691         0          0                1                1         2   
2692         0          0                1                1         2   
2693         1          0                1                2         2   
2694         0          0                4                4         2   

      Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0                       0         1        1             0              0   
1                       0         2        2             0              0   
2                       0         2        1             0              0   
3                       0         1        2             0              0   
4                       2         1        2             0              0   
...                   ...       ...      ...           ...            ...   
2690                    0         4        2             0              0   
2691                    0         3        1             0              0   
2692                    0         1        1             0              0   
2693                    0         5        2             0              0   
2694                    0         4        2             0              0   

      Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  
0                0            0             0             0  
1                0            0             0             0  
2                0            0             0             0  
3                0            0             0             0  
4                0            0             0             0  
...            ...          ...           ...           ...  
2690             0            0             0             0  
2691             0            1             0             0  
2692             0            0             0             0  
2693             0            0             0             0  
2694             1            0             0             0  

[2695 rows x 20 columns]

In [249]:
len(set(merge_data["RN_INDI"]))

589

### 진료파일과 건강검진의 id 유무 비교
- 건강검진의 id가 진료 데이터에 id에 존재하는지 확인

In [250]:
len(set(modify_diagnois_data["MCEX_SICK_SYM"]))

4542

In [251]:
disease_byid = {}
for id in modify_diagnois_data["RN_INDI"]:
    disease_byid[id] = []

In [252]:
len(disease_byid.keys())

997

In [253]:
len(set(diagnois_data["RN_INDI"]))
len(set(screening_data["RN_INDI"]))

395

In [254]:
count = 0
idList = list(set(diagnois_data["RN_INDI"]))
for id in list(set(screening_data["RN_INDI"])):
    if id in idList == False:
        count = count + 1
print(count)

0


### 건강검진 데이터와 진료 데이터 합치기

In [255]:
merge_data["병유형"] = [[] for a in range(len(merge_data))]

In [256]:
merge_data[:10]

EXMD_BZ_YYYY  RN_INDI  HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0          2002   572493      200211          0          0           0   
1          2002   874800      200207          0          0           0   
2          2002    88450      200207          0          0           0   
3          2002    56993      200212          0          0           0   
4          2002   591264      200210          0          0           0   
5          2002   808467      200211          0          0           0   
6          2002   412901      200205          0          0           0   
7          2002   322147      200212          0          0           0   
8          2002   370314      200211          1          0           0   
9          2002   149741      200206          0          0           0   

   Q_FHX_DM  Q_FHX_ETC  Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  ...  \
0         0          0                1                1  ...   
1         0          0                1                1  ...   
2         0          1                1                1  ...   
3         1          0                2                2  ...   
4         0          0                2                2  ...   
5         0          0                2                2  ...   
6         0          0                2                2  ...   
7         0          0                1                1  ...   
8         0          0                2                1  ...   
9         0          0                3                2  ...   

   Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0                    0         1        1             0              0   
1                    0         2        2             0              0   
2                    0         2        1             0              0   
3                    0         1        2             0              0   
4                    2         1        2             0              0   
5                    0         1        2             0              0   
6                    1         1        2             0              0   
7                    0         2        1             0              0   
8                    0         1        1             0              0   
9                    0         2        1             0              0   

   Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  병유형  
0             0            0             0             0   []  
1             0            0             0             0   []  
2             0            0             0             0   []  
3             0            0             0             0   []  
4             0            0             0             0   []  
5             0            0             0             0   []  
6             0            0             0             0   []  
7             0            0             0             0   []  
8             0            0             0             0   []  
9             0            0             0             0   []  

[10 rows x 21 columns]

In [257]:
diseaseList = {}
for data in set(merge_data["RN_INDI"]):
    diseaseList[data] = []
for idx, data in enumerate(set(merge_data["RN_INDI"])):
    diseaseList[data].append(list(modify_diagnois_data[modify_diagnois_data["RN_INDI"]==data]["대분류"]))

In [258]:
merge_data


EXMD_BZ_YYYY  RN_INDI  HME_YYYYMM  Q_FHX_HTN  Q_FHX_STK  Q_FHX_HTDZ  \
0             2002   572493      200211          0          0           0   
1             2002   874800      200207          0          0           0   
2             2002    88450      200207          0          0           0   
3             2002    56993      200212          0          0           0   
4             2002   591264      200210          0          0           0   
...            ...      ...         ...        ...        ...         ...   
2690          2015   266734      201504          0          0           0   
2691          2015   343874      201511          0          0           0   
2692          2015   798472      201507          0          0           0   
2693          2015   720080      201505          0          0           0   
2694          2015   127519      201511          0          0           0   

      Q_FHX_DM  Q_FHX_ETC  Q_DRK_FRQ_V0108  Q_DRK_AMT_V0108  ...  \
0            0          0                1                1  ...   
1            0          0                1                1  ...   
2            0          1                1                1  ...   
3            1          0                2                2  ...   
4            0          0                2                2  ...   
...        ...        ...              ...              ...  ...   
2690         0          1                2                3  ...   
2691         0          0                1                1  ...   
2692         0          0                1                1  ...   
2693         1          0                1                2  ...   
2694         0          0                4                4  ...   

      Q_SMK_NOW_AMT_V0108  Q_PA_FRQ  G1E_BMI  Q_PHX_DX_STK  Q_PHX_DX_HTDZ  \
0                       0         1        1             0              0   
1                       0         2        2             0              0   
2                       0         2        1             0              0   
3                       0         1        2             0              0   
4                       2         1        2             0              0   
...                   ...       ...      ...           ...            ...   
2690                    0         4        2             0              0   
2691                    0         3        1             0              0   
2692                    0         1        1             0              0   
2693                    0         5        2             0              0   
2694                    0         4        2             0              0   

      Q_PHX_DX_HTN  Q_PHX_DX_DM  Q_PHX_DX_PTB  Q_PHX_DX_ETC  병유형  
0                0            0             0             0   []  
1                0            0             0             0   []  
2                0            0             0             0   []  
3                0            0             0             0   []  
4                0            0             0             0   []  
...            ...          ...           ...           ...  ...  
2690             0            0             0             0   []  
2691             0            1             0             0   []  
2692             0            0             0             0   []  
2693             0            0             0             0   []  
2694             1            0             0             0   []  

[2695 rows x 21 columns]

In [259]:
diseaseList.keys()

dict_keys([294913, 829452, 145424, 964637, 587805, 665633, 495650, 92198, 706602, 825387, 215084, 370738, 38967, 301124, 680010, 335948, 815191, 245849, 606303, 358502, 305256, 354421, 725112, 628858, 942204, 909438, 166015, 741504, 739454, 297087, 383109, 948365, 483473, 979090, 237719, 26776, 403607, 805018, 92313, 321692, 473250, 329890, 4263, 688302, 948405, 336055, 637115, 446652, 764100, 356551, 393421, 727245, 979151, 626896, 839897, 483546, 2270, 346335, 698594, 897251, 96484, 6374, 889062, 884968, 637160, 149741, 194801, 674034, 51442, 768249, 153851, 874754, 663811, 753924, 219397, 559370, 971021, 999693, 47374, 762129, 915731, 975124, 334101, 860440, 882980, 422180, 870692, 397613, 874800, 39217, 262452, 559420, 848190, 956735, 452930, 921924, 553285, 444740, 418137, 364892, 41309, 84322, 606567, 80234, 934252, 483693, 88450, 344450, 416133, 637320, 717196, 688532, 45461, 911766, 285079, 321944, 582044, 518558, 979358, 49567, 686497, 760226, 532905, 166324, 264628, 793017, 8

In [260]:
type(merge_data['RN_INDI'][0])

numpy.int32

In [261]:
def to_bigcategory(code):
    if "_" in code:
        return 0
    if len(code) < 1 :
        return 0
    if code.strip()[0] in ["A","B"]:return 1
    elif code.strip()[0] in ["C"]:return 2
    elif code.strip()[0] in ["D"]:
        if int(code[1:3]) <= 48:
            return 2
        elif int(code[1:3]) > 48:
            return 3
    elif code.strip()[0] in ["E"]:return 4
    elif code.strip()[0] in ["F"]:return 5
    elif code.strip()[0] in ["G"]:return 6
    elif code.strip()[0] in ["H"]:
        if int(code[1:3]) <= 59:
            return 7
        elif int(code[1:3]) > 59:
            return 8
    elif code.strip()[0] in ["I"]:return 9
    elif code.strip()[0] in ["J"]:return 10
    elif code.strip()[0] in ["K"]:return 11
    elif code.strip()[0] in ["L"]:return 12
    elif code.strip()[0] in ["M"]:return 13
    elif code.strip()[0] in ["N"]:return 14
    elif code.strip()[0] in ["O"]:return 15
    elif code.strip()[0] in ["P"]:return 16
    elif code.strip()[0] in ["Q"]:return 17
    elif code.strip()[0] in ["R"]:return 18
    elif code.strip()[0] in ["S","T"]:return 19
    elif code.strip()[0] in ["U"]:return 20
    elif code.strip()[0] in ["V","Y"]:return 21
    elif code.strip()[0] in ["Z"]:return 22
    return 0

In [262]:
for idx, data in enumerate(merge_data["RN_INDI"]):
    for code in list(set(diseaseList[data][0])):
        big_category= to_bigcategory(code)
        merge_data["병유형"][idx].append(big_category)

In [263]:
for idx, data in enumerate(merge_data["병유형"]):
    merge_data["병유형"][idx] = list(set(data))

C:\Users\tlsgh\anaconda3\envs\osaesg\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [264]:
merge_data.drop(["EXMD_BZ_YYYY","RN_INDI","HME_YYYYMM"],axis=1,inplace=True)

In [265]:
merge_data.iloc[-100]

Q_FHX_HTN                                                        0
Q_FHX_STK                                                        0
Q_FHX_HTDZ                                                       0
Q_FHX_DM                                                         0
Q_FHX_ETC                                                        1
Q_DRK_FRQ_V0108                                                  2
Q_DRK_AMT_V0108                                                  2
Q_SMK_YN                                                         1
Q_SMK_NOW_AMT_V0108                                              0
Q_PA_FRQ                                                         5
G1E_BMI                                                          1
Q_PHX_DX_STK                                                     0
Q_PHX_DX_HTDZ                                                    0
Q_PHX_DX_HTN                                                     0
Q_PHX_DX_DM                                                   

### AI 모델링


In [266]:
merge_data["병유형"]
label = merge_data["병유형"]

In [267]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
mlb.fit_transform(label)


array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1]])

In [268]:
X_train = np.array(merge_data.drop(["병유형", 'Q_PHX_DX_STK','Q_PHX_DX_HTDZ','Q_PHX_DX_HTN','Q_PHX_DX_DM','Q_PHX_DX_PTB','Q_PHX_DX_ETC'],axis=1)[:-100])
X_test = np.array(merge_data.drop(["병유형", 'Q_PHX_DX_STK','Q_PHX_DX_HTDZ','Q_PHX_DX_HTN','Q_PHX_DX_DM','Q_PHX_DX_PTB','Q_PHX_DX_ETC'],axis=1)[-100:])
y=mlb.fit_transform(label)
y_train= np.array(y[:-100])
y_test = np.array(y[-100:])

In [269]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score
for num in range(1,50):
    print(num)
    print('\n')
    knn_clf = KNeighborsClassifier(n_neighbors=num)
    knn_clf.fit(X_train, y_train)
    y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_train, cv=3)
    print(f1_score(y_train,y_train_knn_pred,average="macro"))

1


0.6058408675630459
2


0.5212550201481391
3


0.5942055108628607
4


0.5649116544786985
5


0.6041890101531507
6


0.5849026935486982
7


0.6076363720341973
8


0.5884356855990682
9


0.6070325647563027
10


0.5908503098845203
11


0.6077981806313553
12


0.5944965045343572
13


0.6080743311953298
14


0.5948007147907565
15


0.6072783816684948
16


0.5949651442575914
17


0.605602384794341
18


0.5948848602517212
19


0.6068744136185891
20


0.5950986025989476
21


0.6014704739889164
22


0.5936087715824674
23


0.604606259285773
24


0.5918958989717656
25


0.6043014303906075
26


0.5943708061256034
27


0.6012575701697033
28


0.5927758128333527
29


0.5990322869594306
30


0.5925238817065035
31


0.5975720877500938
32


0.5902055996200568
33


0.5977319085836089
34


0.5865348849772325
35


0.5952913789095932
36


0.5887039967148064
37


0.594995652188329
38


0.5913670606764342
39


0.5937923783252598
40


0.5897734463590832
41


0.5935954624240695
42


0.58719254690768
43


0

In [270]:
knn_clf = KNeighborsClassifier(n_neighbors=38)
knn_clf.fit(X_train, y_train)
y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_train, cv=3)
print(f1_score(y_train,y_train_knn_pred,average="macro"))

0.5913670606764342


In [271]:
knn_clf.predict_proba(X_test[2].reshape(1,-1))

[array([[0.05263158, 0.94736842]]),
 array([[0.13157895, 0.86842105]]),
 array([[0.65789474, 0.34210526]]),
 array([[0.76315789, 0.23684211]]),
 array([[0.31578947, 0.68421053]]),
 array([[0.44736842, 0.55263158]]),
 array([[0.18421053, 0.81578947]]),
 array([[0.26315789, 0.73684211]]),
 array([[0.34210526, 0.65789474]]),
 array([[0., 1.]]),
 array([[0., 1.]]),
 array([[0., 1.]]),
 array([[0.02631579, 0.97368421]]),
 array([[0.36842105, 0.63157895]]),
 array([[0.89473684, 0.10526316]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[0.02631579, 0.97368421]]),
 array([[0.07894737, 0.92105263]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[0.73684211, 0.26315789]])]

In [272]:
from sklearn.naive_bayes import MultinomialNB
Mnb = MultinomialNB()
Mnb.fit(X_train,y_train)


In [273]:
print(y_train_knn_pred[:10])
print(y_train[:10])

[[1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0]]
[[1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 0 0 0]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1]
 [1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 0]
 [1 1 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1]
 [1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0]]


In [274]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=123456)
rf.fit(X_train, y_train)

RandomForestClassifier(oob_score=True, random_state=123456)

In [275]:
y_train_rf_pred = cross_val_predict(rf, X_train, y_train, cv=3)
print(f1_score(y_train,y_train_knn_pred,average="macro"))

0.5913670606764342


In [276]:
rf.predict_proba(X_test[0].reshape(1,-1))

[array([[0.03582418, 0.96417582]]),
 array([[0.80430403, 0.19569597]]),
 array([[0.85486264, 0.14513736]]),
 array([[0.95500916, 0.04499084]]),
 array([[0.12, 0.88]]),
 array([[0.83012821, 0.16987179]]),
 array([[0.78081502, 0.21918498]]),
 array([[0.81499084, 0.18500916]]),
 array([[0.85499084, 0.14500916]]),
 array([[0.03499084, 0.96500916]]),
 array([[0., 1.]]),
 array([[0.01499084, 0.98500916]]),
 array([[0.01582418, 0.98417582]]),
 array([[0.16012821, 0.83987179]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[0.75, 0.25]]),
 array([[0., 1.]]),
 array([[0.99, 0.01]]),
 array([[1., 0.]]),
 array([[0.88, 0.12]])]

In [277]:
import pickle
import joblib

In [283]:
joblib.dump(rf,'./data/rf_model.pkl')

['./data/rf_model.pkl']

In [279]:
loaded_model = joblib.load('./data/rf_model.pkl')

In [285]:
a= loaded_model.predict_proba(X_test[10].reshape(1,-1))

In [292]:
s=[b[0][1]for b in a]
k= sorted(range(len(s)),key=lambda k:s[k],reverse=True)
print(k)

[9, 17, 10, 18, 1, 11, 12, 7, 6, 0, 5, 4, 8, 3, 13, 2, 21, 20, 14, 15, 16, 19]


In [281]:
ab = []
for col,item in merge_data.iteritems():
    ab.append(col)
    print(col)
    print(set(item))

Q_FHX_HTN
{0, 1}
Q_FHX_STK
{0, 1}
Q_FHX_HTDZ
{0, 1}
Q_FHX_DM
{0, 1}
Q_FHX_ETC
{0, 1}
Q_DRK_FRQ_V0108
{1, 2, 3, 4, 5}
Q_DRK_AMT_V0108
{1, 2, 3, 4}
Q_SMK_YN
{1, 2, 3}
Q_SMK_NOW_AMT_V0108
{0, 1, 2, 3, 4}
Q_PA_FRQ
{1, 2, 3, 4, 5}
G1E_BMI
{0, 1, 2, 3}
Q_PHX_DX_STK
{0, 1}
Q_PHX_DX_HTDZ
{0, 1}
Q_PHX_DX_HTN
{0, 1}
Q_PHX_DX_DM
{0, 1}
Q_PHX_DX_PTB
{0, 1}
Q_PHX_DX_ETC
{0, 1}
병유형


TypeError: unhashable type: 'list'

In [ ]:
BMI = a["weight"]/(a["height"]/100)**2
a["family_stroke"],a["family_heart"],a["family_highBlood"],a["family_diabetes"],a["family_etc"],a["drink_count"],a["drink_amount"],a["smoke_yn"],a["smoke_amount"],a["exercise_count"],BMI

In [282]:
np.shape(X_test[0])

(11,)